version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
