#!/bin/bash
SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR

. $SCRIPT_DIR/.env
. $SCRIPT_DIR/.credentials

if [ -d common_infra ]; then
    . $SCRIPT_DIR/common_infra/run_functions
else
    >&2 echo "Project requires common_infra"
    exit 1
fi
export pidfile="./work/.$SCRIPTNAME.pid"
start_this() {
    . $SCRIPT_DIR/venv/bin/activate
    python $SCRIPT_DIR/sync_jelly_kodi.py
}

start
